### ISSUE TITLE
Getting error: "duplicate definition of '<cluster>:namespace/demo' (in namespaces/demo.yaml and namespaces/demo.yaml)"

### ISSUE THREAD

**Issue by youknowjack** [weaveworks/flux-get-started#11]
I was just following the straightforward Getting Started instructions at https://github.com/weaveworks/flux/blob/master/site/get-started.md and when I get to running the demo it fails. In the logs:
`ts=2019-05-25T14:09:27.291146795Z caller=loop.go:90 component=sync-loop err="loading resources from repo: duplicate definition of '<cluster>:namespace/demo' (in namespaces/demo.yaml and namespaces/demo.yaml)"`

Running in minikube on Mac .

Any pointers?

**Comment by stefanprodan** [comment]
I can't reproduce this on Kubernetes Kind or GKE.
